set -g set-clipboard on

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",xterm-ghostty:RGB"
set -sa terminal-features ",xterm-ghostty:RGB"
set -s escape-time 0
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -g focus-events on
setw -g aggressive-resize on
setw -g mode-keys vi
set -g mouse on

set -g prefix C-b
bind C-b send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-left-length 100
set -g status-right-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"

bind c new-window -c "#{pane_current_path}"

run ~/.config/tmux/plugins/tmux-resurrect/resurrect.tmux
run ~/.config/tmux/plugins/tmux-continuum/continuum.tmux
