set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",xterm-ghostty:RGB"
set -sa terminal-features ",xterm-ghostty:RGB"
set -s escape-time 0
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -g focus-events on
setw -g aggressive-resize on
setw -g mode-keys vi
set -g mouse on

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.tmux.conf \; display "Config reloaded!"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g status-position bottom
set -g status-justify left
set -g status-left-length 30
set -g status-right-length 100

set -g status-left "#[fg=green]#S "
set -g status-right "#[fg=yellow]%H:%M #[fg=cyan]%d-%b-%y"

setw -g window-status-current-style fg=white,bg=default,bold
setw -g window-status-format "#[fg=colour244]#I #[fg=colour244]#W"
setw -g window-status-current-format "#[fg=white]#I #[fg=white]#W"

bind c new-window -c "#{pane_current_path}"
